spring:
  datasource:
    url: jdbc:mysql://118.31.171.202:3306/db_spzx?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: db_spzx
    password: K2eExSnDR4AYXmAX
    driver-class-name: com.mysql.cj.jdbc.Driver
# redis配置
  redis:
    password: root
    port: 6379
    host: 118.31.171.202

#更改端口号为80
server:
  port: 3000
mybatis-plus:
  # 指定sql映射文件位置
  mapper-locations: classpath:/mapper/*/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl