spring:
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.209.144:3306/shops_database?useUnicode=true&characterEncoding=utf8
  thymeleaf:
    cache: false
  #配置需要访问的静态资源目录
  resources:
    static-locations: classpath:/templates/,classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
  mail:
    host: smtp.qq.com
    username: 1919796303@qq.com
    password: lvletvzbachqgidj
    default-encoding: utf-8

#  session:
#    store-type: jdbc
# redis配置

mybatis:
  # 驼峰命名
  configuration:
    map-underscore-to-camel-case: true
  #config-location: classpath:mybatis/mybatis-config.xml
  # 指定sql映射文件位置
  mapper-locations: classpath:mybatis/mapper/*.xml
#更改端口号为80
server:
  port: 80
