spring:
  datasource:
    url: jdbc:mysql://118.31.171.202:3306/db_spzx?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: db_spzx
    password: K2eExSnDR4AYXmAX
    driver-class-name: com.mysql.cj.jdbc.Driver
# redis配置
  redis:
    password: root
    port: 6379
    host: 118.31.171.202

mybatis:
  # 驼峰命名
  configuration:
    map-underscore-to-camel-case: true
  #config-location: classpath:mybatis/mybatis-config.xml
  # 指定sql映射文件位置
  mapper-locations: classpath:mybatis/mapper/*.xml
#更改端口号为80
server:
  port: 80
